# Generated by Django 5.1.4 on 2024-12-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_graduated', models.IntegerField()),
                ('courses_completed', models.IntegerField()),
                ('graduates_count', models.IntegerField()),
            ],
        ),
    ]
