# Generated by Django 5.1.4 on 2024-12-10 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_message_thoughts'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.course')),
                ('duration', models.DurationField()),
                ('video_link', models.URLField()),
                ('title', models.TextField()),
                ('video_link_url', models.URLField()),
                ('homework_type', models.CharField(choices=[('description', 'Description'), ('link', 'Link'), ('list', 'List')], max_length=50)),
                ('homework_content', models.TextField()),
            ],
        ),
    ]
