# Generated by Django 5.1.4 on 2024-12-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_emailsubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetail',
            old_name='homework_content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='homework_type',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='title',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='video_link_url',
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='izox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.coursetype'),
            preserve_default=False,
        ),
    ]
