# Generated by Django 5.1.4 on 2024-12-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_coursedetail_id_alter_coursedetail_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseschedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='CourseDetail',
        ),
        migrations.DeleteModel(
            name='CourseSchedule',
        ),
    ]
