# Generated by Django 5.1.4 on 2024-12-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_coursedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedetail',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='coursedetail',
            name='teacher',
        ),
    ]
