# Generated by Django 5.1.4 on 2024-12-11 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_coursedetail_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseDetail',
        ),
    ]
