# Generated by Django 5.1.4 on 2024-12-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_coursedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
